//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MewingLab.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MewingLabEntities4 : DbContext
    {
        public MewingLabEntities4()
            : base("name=MewingLabEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analyzer> analyzer { get; set; }
        public virtual DbSet<biomaterials> biomaterials { get; set; }
        public virtual DbSet<insurance_company> insurance_company { get; set; }
        public virtual DbSet<insurance_type> insurance_type { get; set; }
        public virtual DbSet<login_status> login_status { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<orders_statuses> orders_statuses { get; set; }
        public virtual DbSet<patients> patients { get; set; }
        public virtual DbSet<results> results { get; set; }
        public virtual DbSet<services> services { get; set; }
        public virtual DbSet<services_in_order> services_in_order { get; set; }
        public virtual DbSet<services_in_user> services_in_user { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_history> users_history { get; set; }
        public virtual DbSet<users_types> users_types { get; set; }
    }
}
