//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MewingLab.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public orders()
        {
            this.results = new HashSet<results>();
            this.services_in_order = new HashSet<services_in_order>();
        }
    
        public int id { get; set; }
        public int id_order_status { get; set; }
        public Nullable<int> day_in_work { get; set; }
        public System.DateTime creation_date { get; set; }
        public int id_user { get; set; }
        public int number { get; set; }
        public int id_patient { get; set; }
        public int id_biomaterial { get; set; }
        public Nullable<double> summ { get; set; }
    
        public virtual biomaterials biomaterials { get; set; }
        public virtual orders_statuses orders_statuses { get; set; }
        public virtual patients patients { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<results> results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<services_in_order> services_in_order { get; set; }
    }
}
