//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MewingLab.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_in_user
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int id_service { get; set; }
    
        public virtual services services { get; set; }
        public virtual users users { get; set; }
    }
}
