//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MewingLab.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class services_in_order
    {
        public int id { get; set; }
        public int id_order { get; set; }
        public int id_service { get; set; }
        public int id_status { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual orders_statuses orders_statuses { get; set; }
        public virtual services services { get; set; }

        public override string ToString()
        {
            return $"{id}. {services.name} ({orders.patients.second_name} {orders.patients.name})";
        }
    }
}
