//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MewingLab.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_history
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public int id_login_status { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual login_status login_status { get; set; }
        public virtual users users { get; set; }

        public override string ToString()
        {
            return $"{id}. попытка входа {users.login} в {time}. Статус: {login_status.name}";
        }
    }
}
